In [1]:
#import required libraries
import pandas as pd
import numpy as np

In [2]:
#import train and test data set
train_df = pd.read_csv('train.csv')
test_df = pd.read_csv('test.csv')

In [3]:
#train head
train_df.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [4]:
#train set shape
train_df.shape

(4209, 378)

In [5]:
#test head 
test_df.head()

ID  X0 X1  X2 X3 X4 X5 X6 X8  X10  ...  X375  X376  X377  X378  X379  X380  \
0   1  az  v   n  f  d  t  a  w    0  ...     0     0     0     1     0     0   
1   2   t  b  ai  a  d  b  g  y    0  ...     0     0     1     0     0     0   
2   3  az  v  as  f  d  a  j  j    0  ...     0     0     0     1     0     0   
3   4  az  l   n  f  d  z  l  n    0  ...     0     0     0     1     0     0   
4   5   w  s  as  c  d  y  i  m    0  ...     1     0     0     0     0     0   

   X382  X383  X384  X385  
0     0     0     0     0  
1     0     0     0     0  
2     0     0     0     0  
3     0     0     0     0  
4     0     0     0     0  

[5 rows x 377 columns]

In [6]:
test_df.shape

(4209, 377)

In [7]:
test_df.columns

Index(['ID', 'X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8', 'X10',
       ...
       'X375', 'X376', 'X377', 'X378', 'X379', 'X380', 'X382', 'X383', 'X384',
       'X385'],
      dtype='object', length=377)

In [8]:
train_df.y

0       130.81
1        88.53
2        76.26
3        80.62
4        78.02
         ...  
4204    107.39
4205    108.77
4206    109.22
4207     87.48
4208    110.85
Name: y, Length: 4209, dtype: float64

In [9]:
train_df['X1'].unique()

array(['v', 't', 'w', 'b', 'r', 'l', 's', 'aa', 'c', 'a', 'e', 'h', 'z',
       'j', 'o', 'u', 'p', 'n', 'i', 'y', 'd', 'f', 'm', 'k', 'g', 'q',
       'ab'], dtype=object)

In [10]:
train_df['X2'].unique()

array(['at', 'av', 'n', 'e', 'as', 'aq', 'r', 'ai', 'ak', 'm', 'a', 'k',
       'ae', 's', 'f', 'd', 'ag', 'ay', 'ac', 'ap', 'g', 'i', 'aw', 'y',
       'b', 'ao', 'al', 'h', 'x', 'au', 't', 'an', 'z', 'ah', 'p', 'am',
       'j', 'q', 'af', 'l', 'aa', 'c', 'o', 'ar'], dtype=object)

In [11]:
train_df.isna().sum()

ID      0
y       0
X0      0
X1      0
X2      0
       ..
X380    0
X382    0
X383    0
X384    0
X385    0
Length: 378, dtype: int64

In [12]:
#check the varience of data
train_df_variance = train_df.var(axis=0)
train_df_variance

ID      5.941936e+06
y       1.607667e+02
X10     1.313092e-02
X11     0.000000e+00
X12     6.945713e-02
            ...     
X380    8.014579e-03
X382    7.546747e-03
X383    1.660732e-03
X384    4.750593e-04
X385    1.423823e-03
Length: 370, dtype: float64

**create data frame  for calculating variance**

In [13]:
train_var_df = pd.DataFrame(train_df_variance)
train_var_df

0
ID    5.941936e+06
y     1.607667e+02
X10   1.313092e-02
X11   0.000000e+00
X12   6.945713e-02
...            ...
X380  8.014579e-03
X382  7.546747e-03
X383  1.660732e-03
X384  4.750593e-04
X385  1.423823e-03

[370 rows x 1 columns]

In [14]:
#transpose dataframe
train_var_df = train_var_df.T
train_var_df

ID          y       X10  X11       X12       X13       X14  \
0  5.941936e+06  160.76671  0.013131  0.0  0.069457  0.054623  0.244893   

        X15       X16       X17  ...      X375      X376      X377      X378  \
0  0.000475  0.002607  0.007547  ...  0.217233  0.053993  0.215753  0.020248   

       X379      X380      X382      X383      X384      X385  
0  0.009415  0.008015  0.007547  0.001661  0.000475  0.001424  

[1 rows x 370 columns]

In [17]:
#create data frame list

columns= list(train_var_df)

In [19]:
columns[0:5]

['ID', 'y', 'X10', 'X11', 'X12']

**List the columns of the DataFrame having 0 as the Variance**

In [22]:
for i in columns:
    if train_var_df[i][0]==0:
        print(i,train_var_df[i][0] )
    

X11 0.0
X93 0.0
X107 0.0
X233 0.0
X235 0.0
X268 0.0
X289 0.0
X290 0.0
X293 0.0
X297 0.0
X330 0.0
X347 0.0


**Drop the columns having 0 as their Variance in the DataFrame**

In [23]:
train_df = train_df.drop(['X11','X93','X107','X233','X235','X268','X289','X290','X293','X297','X330','X347'], axis=1)

In [24]:
train_df.shape

(4209, 366)

In [26]:
train_df.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 366 columns]

In [28]:
#train data back up
train_df_back_up = train_df
train_df_back_up.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 366 columns]

**# Find Missing values in the DataFrame**

In [29]:
# Find Missing values in the DataFrame
miss_value_data= train_df.isna().any()
miss_value_data

ID      False
y       False
X0      False
X1      False
X2      False
        ...  
X380    False
X382    False
X383    False
X384    False
X385    False
Length: 366, dtype: bool

**Push the Boolean Data into a csv to analyze**

In [30]:
miss_value_data.to_csv('miss_value_df.csv')

/home/snk/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  """Entry point for launching an IPython kernel.


**find the unique value data sets**

In [31]:
train_df['X10'].unique()

array([0, 1])

In [33]:
train_df_ID = train_df['ID'].unique()

In [34]:
train_df_ID

array([   0,    6,    7, ..., 8412, 8415, 8417])

In [35]:
train_df_ID.shape

(4209,)

In [37]:
train_df['X0'].unique()

array(['k', 'az', 't', 'al', 'o', 'w', 'j', 'h', 's', 'n', 'ay', 'f', 'x',
       'y', 'aj', 'ak', 'am', 'z', 'q', 'at', 'ap', 'v', 'af', 'a', 'e',
       'ai', 'd', 'aq', 'c', 'aa', 'ba', 'as', 'i', 'r', 'b', 'ax', 'bc',
       'u', 'ad', 'au', 'm', 'l', 'aw', 'ao', 'ac', 'g', 'ab'],
      dtype=object)

In [38]:
train_df['X1'].unique()

array(['v', 't', 'w', 'b', 'r', 'l', 's', 'aa', 'c', 'a', 'e', 'h', 'z',
       'j', 'o', 'u', 'p', 'n', 'i', 'y', 'd', 'f', 'm', 'k', 'g', 'q',
       'ab'], dtype=object)

**drop the duplicates in datasets**

In [39]:
train_df_final = train_df.drop_duplicates()

In [40]:
train_df_final.shape

(4209, 366)

**create dependent and independentent feature**

In [41]:
y = train_df_final['y']
X = train_df_final.drop(['y'],axis=1)

In [42]:
y

0       130.81
1        88.53
2        76.26
3        80.62
4        78.02
         ...  
4204    107.39
4205    108.77
4206    109.22
4207     87.48
4208    110.85
Name: y, Length: 4209, dtype: float64

In [43]:
X

ID  X0 X1  X2 X3 X4  X5 X6 X8  X10  ...  X375  X376  X377  X378  X379  \
0        0   k  v  at  a  d   u  j  o    0  ...     0     0     1     0     0   
1        6   k  t  av  e  d   y  l  o    0  ...     1     0     0     0     0   
2        7  az  w   n  c  d   x  j  x    0  ...     0     0     0     0     0   
3        9  az  t   n  f  d   x  l  e    0  ...     0     0     0     0     0   
4       13  az  v   n  f  d   h  d  n    0  ...     0     0     0     0     0   
...    ...  .. ..  .. .. ..  .. .. ..  ...  ...   ...   ...   ...   ...   ...   
4204  8405  ak  s  as  c  d  aa  d  q    0  ...     1     0     0     0     0   
4205  8406   j  o   t  d  d  aa  h  h    0  ...     0     1     0     0     0   
4206  8412  ak  v   r  a  d  aa  g  e    0  ...     0     0     1     0     0   
4207  8415  al  r   e  f  d  aa  l  u    0  ...     0     0     0     0     0   
4208  8417   z  r  ae  c  d  aa  g  w    0  ...     1     0     0     0     0   

      X380  X382  X383  X384  X385  
0        0     0     0     0     0  
1        0     0     0     0     0  
2        0     1     0     0     0  
3        0     0     0     0     0  
4        0     0     0     0     0  
...    ...   ...   ...   ...   ...  
4204     0     0     0     0     0  
4205     0     0     0     0     0  
4206     0     0     0     0     0  
4207     0     0     0     0     0  
4208     0     0     0     0     0  

[4209 rows x 365 columns]

**X in to numpy array**

In [46]:
X = X.to_numpy()

AttributeError: 'numpy.ndarray' object has no attribute 'to_numpy'

In [47]:
X

array([[0, 'k', 'v', ..., 0, 0, 0],
       [6, 'k', 't', ..., 0, 0, 0],
       [7, 'az', 'w', ..., 0, 0, 0],
       ...,
       [8412, 'ak', 'v', ..., 0, 0, 0],
       [8415, 'al', 'r', ..., 0, 0, 0],
       [8417, 'z', 'r', ..., 0, 0, 0]], dtype=object)

**Label Encoder Function for to the Independent Dataset X applicable variables**

In [48]:
def label_encode(i):
    from sklearn.preprocessing import LabelEncoder, OneHotEncoder
    label_encoder = LabelEncoder()
    X[: , i] =label_encoder.fit_transform( X[: , i])
    onehotencoder = OneHotEncoder(handle_unknown='ignore')
    return onehotencoder

In [59]:
#for x0 to x8
for i in range(1,9):
    label_encode(i)

In [60]:
X[0:8]

array([[0, 32, 23, ..., 0, 0, 0],
       [6, 32, 21, ..., 0, 0, 0],
       [7, 20, 24, ..., 0, 0, 0],
       ...,
       [18, 40, 3, ..., 0, 0, 0],
       [24, 9, 19, ..., 0, 0, 0],
       [25, 36, 13, ..., 0, 0, 0]], dtype=object)

In [61]:
#cover X , numpy array into data frame
X_df = pd.DataFrame(X)

In [62]:
X_df.head()

0   1   2   3   4   5   6   7   8   9    ... 355 356 357 358 359 360 361  \
0   0  32  23  17   0   3  24   9  14   0  ...   0   0   1   0   0   0   0   
1   6  32  21  19   4   3  28  11  14   0  ...   1   0   0   0   0   0   0   
2   7  20  24  34   2   3  27   9  23   0  ...   0   0   0   0   0   0   1   
3   9  20  21  34   5   3  27  11   4   0  ...   0   0   0   0   0   0   0   
4  13  20  23  34   5   3  12   3  13   0  ...   0   0   0   0   0   0   0   

  362 363 364  
0   0   0   0  
1   0   0   0  
2   0   0   0  
3   0   0   0  
4   0   0   0  

[5 rows x 365 columns]

In [63]:
y

0       130.81
1        88.53
2        76.26
3        80.62
4        78.02
         ...  
4204    107.39
4205    108.77
4206    109.22
4207     87.48
4208    110.85
Name: y, Length: 4209, dtype: float64

In [65]:
#convert y into data frame
y_df = pd.DataFrame(y)
y_df.head()

y
0  130.81
1   88.53
2   76.26
3   80.62
4   78.02

In [68]:
#check the standardscaler
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X_df)
X

array([[-1.72565045,  0.16301209,  1.39348787, ..., -0.04081511,
        -0.02180363, -0.03778296],
       [-1.72318873,  0.16301209,  1.15902093, ..., -0.04081511,
        -0.02180363, -0.03778296],
       [-1.72277844, -0.71055977,  1.51072134, ..., -0.04081511,
        -0.02180363, -0.03778296],
       ...,
       [ 1.72568262, -1.58413164,  1.39348787, ..., -0.04081511,
        -0.02180363, -0.03778296],
       [ 1.72691348, -1.51133398,  0.924554  , ..., -0.04081511,
        -0.02180363, -0.03778296],
       [ 1.72773405,  1.18217927,  0.924554  , ..., -0.04081511,
        -0.02180363, -0.03778296]])

**Apply PCA for X**

In [72]:
from mlxtend.preprocessing import standardize
from sklearn.decomposition import PCA
X = standardize(X)
X

array([[-1.72565045,  0.16301209,  1.39348787, ..., -0.04081511,
        -0.02180363, -0.03778296],
       [-1.72318873,  0.16301209,  1.15902093, ..., -0.04081511,
        -0.02180363, -0.03778296],
       [-1.72277844, -0.71055977,  1.51072134, ..., -0.04081511,
        -0.02180363, -0.03778296],
       ...,
       [ 1.72568262, -1.58413164,  1.39348787, ..., -0.04081511,
        -0.02180363, -0.03778296],
       [ 1.72691348, -1.51133398,  0.924554  , ..., -0.04081511,
        -0.02180363, -0.03778296],
       [ 1.72773405,  1.18217927,  0.924554  , ..., -0.04081511,
        -0.02180363, -0.03778296]])

In [74]:
#PCA 
pca = PCA(n_components=0.95)
X_pca= pca.fit_transform(X)

In [75]:
X_pca

array([[12.2479426 , -2.94616767, -0.96889421, ...,  0.51287931,
         0.32836243,  0.40810799],
       [-0.10761082,  0.3647402 ,  0.98997272, ..., -0.63789247,
        -0.7327322 ,  0.21586011],
       [10.27291072, 21.10326107, -5.02216176, ...,  2.19701707,
        -1.41189662,  0.80878726],
       ...,
       [ 0.44231616,  0.8989563 ,  3.45276206, ...,  0.20010703,
        -0.16012722, -0.60824249],
       [-1.33649135,  0.59062955, -0.10217684, ..., -0.22789064,
         0.17589921, -0.50716209],
       [-2.16301364, -1.05903452, -0.28051994, ...,  0.41035909,
         1.36150953, -0.63146337]])

In [76]:
#pca arry to data frame
X_pca_df =pd.DataFrame(X_pca)

In [78]:
X_pca_df.shape

(4209, 122)

**split train and test fromdatasets**

In [84]:
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from sklearn.metrics import accuracy_score

X_train,X_test, y_train, y_test =train_test_split(X_pca_df, y_df, test_size =0.3,random_state=0)

**Creating a model using XGBRegressor**

In [82]:
XGBRegressor()

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0,
             importance_type='gain', learning_rate=0.1, max_delta_step=0,
             max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=None, subsample=1, verbosity=1)

In [83]:
model =XGBRegressor(booster='gbtree', gamma=0, learning_rate=0.1,max_depth=3, 
                    min_child_weight=1, n_estimators=100,objective='reg:squarederror', 
                    random_state=0,eg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None, verbosity=1)

In [85]:
model.fit(X_train, y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, eg_alpha=0, gamma=0,
             importance_type='gain', learning_rate=0.1, max_delta_step=0,
             max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
             n_jobs=1, nthread=None, objective='reg:squarederror',
             random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
             seed=None, silent=None, subsample=1, verbosity=1)

In [86]:
y_predict = model.predict(X_test)

In [87]:
y_predict

array([107.58251 ,  94.77818 , 113.722046, ..., 109.98449 ,  92.9361  ,
       100.0562  ], dtype=float32)

In [89]:
##accuracy matric
import sklearn.metrics as metrics

In [91]:
#r2 score
r2_score = metrics.r2_score(y_test, y_predict)

In [95]:
print("r2 score is ",r2_score)

r2 score is  0.45132542305418144


In [93]:
#adjusted r2 score error
adjust_r2_error = 1- (1-r2_score)*(len(y_predict)-1)/(len(y_predict)-X_test.shape[1]-1)

In [96]:
print("adjusted r2 score error is ",adjust_r2_error)

adjusted r2 score error is  0.39260761745120787
