In [1]:
# Import the necessary libraries

In [2]:
import numpy as np
import pandas as pd

In [3]:
# Load the train data

In [4]:
benz_train_data = pd.read_csv('train.csv')

In [5]:
benz_train_data

ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k  v  at  a  d   u  j  o  ...     0     0     1     0   
1        6   88.53   k  t  av  e  d   y  l  o  ...     1     0     0     0   
2        7   76.26  az  w   n  c  d   x  j  x  ...     0     0     0     0   
3        9   80.62  az  t   n  f  d   x  l  e  ...     0     0     0     0   
4       13   78.02  az  v   n  f  d   h  d  n  ...     0     0     0     0   
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4207  8415   87.48  al  r   e  f  d  aa  l  u  ...     0     0     0     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
1        0     0     0     0     0     0  
2        0     0     1     0     0     0  
3        0     0     0     0     0     0  
4        0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4207     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[4209 rows x 378 columns]

In [6]:
# Calculate the Variance for columns of the dataframe

In [7]:
benz_train_data_var = benz_train_data.var(axis=0)
benz_train_data_var

ID      5.941936e+06
y       1.607667e+02
X10     1.313092e-02
X11     0.000000e+00
X12     6.945713e-02
            ...     
X380    8.014579e-03
X382    7.546747e-03
X383    1.660732e-03
X384    4.750593e-04
X385    1.423823e-03
Length: 370, dtype: float64

In [8]:
# Create a DataFrame for the calculated Variance

In [9]:
benz_train_data_var_df = pd.DataFrame(benz_train_data_var)
benz_train_data_var_df

0
ID    5.941936e+06
y     1.607667e+02
X10   1.313092e-02
X11   0.000000e+00
X12   6.945713e-02
...            ...
X380  8.014579e-03
X382  7.546747e-03
X383  1.660732e-03
X384  4.750593e-04
X385  1.423823e-03

[370 rows x 1 columns]

In [10]:
# Transpose the DataFrame been created

In [11]:
benz_train_data_var_df = benz_train_data_var_df.T
benz_train_data_var_df

ID          y       X10  X11       X12       X13       X14  \
0  5.941936e+06  160.76671  0.013131  0.0  0.069457  0.054623  0.244893   

        X15       X16       X17  ...      X375      X376      X377      X378  \
0  0.000475  0.002607  0.007547  ...  0.217233  0.053993  0.215753  0.020248   

       X379      X380      X382      X383      X384      X385  
0  0.009415  0.008015  0.007547  0.001661  0.000475  0.001424  

[1 rows x 370 columns]

In [12]:
# Create a list for the DataFrame

In [13]:
colms = list(benz_train_data_var_df)

In [14]:
# List the columns of the DataFrame having 0 as the Variance

In [15]:
for i in colms:
    if(benz_train_data_var_df[i][0] == 0):
        print(i, benz_train_data_var_df[i][0])    

X11 0.0
X93 0.0
X107 0.0
X233 0.0
X235 0.0
X268 0.0
X289 0.0
X290 0.0
X293 0.0
X297 0.0
X330 0.0
X347 0.0


In [16]:
# Drop the columns having 0 as their Variance in the DataFrame

In [17]:
benz_train_data = benz_train_data.drop(['X11', 'X93', 'X107', 'X233', 'X235', 'X268', 'X289', 'X290', 'X293', 'X297', 'X330', 'X347'], axis =1)
benz_train_data

ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k  v  at  a  d   u  j  o  ...     0     0     1     0   
1        6   88.53   k  t  av  e  d   y  l  o  ...     1     0     0     0   
2        7   76.26  az  w   n  c  d   x  j  x  ...     0     0     0     0   
3        9   80.62  az  t   n  f  d   x  l  e  ...     0     0     0     0   
4       13   78.02  az  v   n  f  d   h  d  n  ...     0     0     0     0   
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4207  8415   87.48  al  r   e  f  d  aa  l  u  ...     0     0     0     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
1        0     0     0     0     0     0  
2        0     0     1     0     0     0  
3        0     0     0     0     0     0  
4        0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4207     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[4209 rows x 366 columns]

In [18]:
benz_train_data_bk = benz_train_data
benz_train_data_bk

ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k  v  at  a  d   u  j  o  ...     0     0     1     0   
1        6   88.53   k  t  av  e  d   y  l  o  ...     1     0     0     0   
2        7   76.26  az  w   n  c  d   x  j  x  ...     0     0     0     0   
3        9   80.62  az  t   n  f  d   x  l  e  ...     0     0     0     0   
4       13   78.02  az  v   n  f  d   h  d  n  ...     0     0     0     0   
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4207  8415   87.48  al  r   e  f  d  aa  l  u  ...     0     0     0     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
1        0     0     0     0     0     0  
2        0     0     1     0     0     0  
3        0     0     0     0     0     0  
4        0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4207     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[4209 rows x 366 columns]

In [19]:
# Find Missing values in the DataFrame

In [20]:
miss_value_df = benz_train_data.isna().any()
miss_value_df

ID      False
y       False
X0      False
X1      False
X2      False
        ...  
X380    False
X382    False
X383    False
X384    False
X385    False
Length: 366, dtype: bool

In [21]:
# Push the Boolean Data into a csv to analyze

In [22]:
miss_value_df.to_csv('Bool_values.csv')

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  """Entry point for launching an IPython kernel.


In [23]:
# Find Unique Values in the Dataset

In [24]:
benz_train_data['X10'].unique()

array([0, 1])

In [25]:
benz_train_ID = benz_train_data.ID.unique()
benz_train_ID

array([   0,    6,    7, ..., 8412, 8415, 8417])

In [26]:
benz_train_ID.shape

(4209,)

In [27]:
benz_train_X0 = benz_train_data.X0.unique()
benz_train_X0

array(['k', 'az', 't', 'al', 'o', 'w', 'j', 'h', 's', 'n', 'ay', 'f', 'x',
       'y', 'aj', 'ak', 'am', 'z', 'q', 'at', 'ap', 'v', 'af', 'a', 'e',
       'ai', 'd', 'aq', 'c', 'aa', 'ba', 'as', 'i', 'r', 'b', 'ax', 'bc',
       'u', 'ad', 'au', 'm', 'l', 'aw', 'ao', 'ac', 'g', 'ab'],
      dtype=object)

In [28]:
benz_train_X0.shape

(47,)

In [29]:
benz_train_data

ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k  v  at  a  d   u  j  o  ...     0     0     1     0   
1        6   88.53   k  t  av  e  d   y  l  o  ...     1     0     0     0   
2        7   76.26  az  w   n  c  d   x  j  x  ...     0     0     0     0   
3        9   80.62  az  t   n  f  d   x  l  e  ...     0     0     0     0   
4       13   78.02  az  v   n  f  d   h  d  n  ...     0     0     0     0   
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4207  8415   87.48  al  r   e  f  d  aa  l  u  ...     0     0     0     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
1        0     0     0     0     0     0  
2        0     0     1     0     0     0  
3        0     0     0     0     0     0  
4        0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4207     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[4209 rows x 366 columns]

In [30]:
# Drop the Duplicates in the Dataset

In [31]:
benz_train_data_final = benz_train_data.drop_duplicates()
benz_train_data_final

ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k  v  at  a  d   u  j  o  ...     0     0     1     0   
1        6   88.53   k  t  av  e  d   y  l  o  ...     1     0     0     0   
2        7   76.26  az  w   n  c  d   x  j  x  ...     0     0     0     0   
3        9   80.62  az  t   n  f  d   x  l  e  ...     0     0     0     0   
4       13   78.02  az  v   n  f  d   h  d  n  ...     0     0     0     0   
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4207  8415   87.48  al  r   e  f  d  aa  l  u  ...     0     0     0     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
1        0     0     0     0     0     0  
2        0     0     1     0     0     0  
3        0     0     0     0     0     0  
4        0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4207     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[4209 rows x 366 columns]

In [32]:
# Create Dependent and Independent Variables from the Dataset

In [33]:
y = benz_train_data_final['y']
X = benz_train_data_final.drop(['y'], axis=1)

In [34]:
X

ID  X0 X1  X2 X3 X4  X5 X6 X8  X10  ...  X375  X376  X377  X378  X379  \
0        0   k  v  at  a  d   u  j  o    0  ...     0     0     1     0     0   
1        6   k  t  av  e  d   y  l  o    0  ...     1     0     0     0     0   
2        7  az  w   n  c  d   x  j  x    0  ...     0     0     0     0     0   
3        9  az  t   n  f  d   x  l  e    0  ...     0     0     0     0     0   
4       13  az  v   n  f  d   h  d  n    0  ...     0     0     0     0     0   
...    ...  .. ..  .. .. ..  .. .. ..  ...  ...   ...   ...   ...   ...   ...   
4204  8405  ak  s  as  c  d  aa  d  q    0  ...     1     0     0     0     0   
4205  8406   j  o   t  d  d  aa  h  h    0  ...     0     1     0     0     0   
4206  8412  ak  v   r  a  d  aa  g  e    0  ...     0     0     1     0     0   
4207  8415  al  r   e  f  d  aa  l  u    0  ...     0     0     0     0     0   
4208  8417   z  r  ae  c  d  aa  g  w    0  ...     1     0     0     0     0   

      X380  X382  X383  X384  X385  
0        0     0     0     0     0  
1        0     0     0     0     0  
2        0     1     0     0     0  
3        0     0     0     0     0  
4        0     0     0     0     0  
...    ...   ...   ...   ...   ...  
4204     0     0     0     0     0  
4205     0     0     0     0     0  
4206     0     0     0     0     0  
4207     0     0     0     0     0  
4208     0     0     0     0     0  

[4209 rows x 365 columns]

In [35]:
y

0       130.81
1        88.53
2        76.26
3        80.62
4        78.02
         ...  
4204    107.39
4205    108.77
4206    109.22
4207     87.48
4208    110.85
Name: y, Length: 4209, dtype: float64

In [36]:
# Convert X DataFrame into an Array

In [37]:
X = X.to_numpy()

In [38]:
X

array([[0, 'k', 'v', ..., 0, 0, 0],
       [6, 'k', 't', ..., 0, 0, 0],
       [7, 'az', 'w', ..., 0, 0, 0],
       ...,
       [8412, 'ak', 'v', ..., 0, 0, 0],
       [8415, 'al', 'r', ..., 0, 0, 0],
       [8417, 'z', 'r', ..., 0, 0, 0]], dtype=object)

In [39]:
# Label Encoder Function for the Dataset and apply to the Independent Dataset X applicable variables

In [40]:
def encode_function_train(i):
    from sklearn.preprocessing import LabelEncoder, OneHotEncoder
    labelencoder_X = LabelEncoder()
    X[:, i] = labelencoder_X.fit_transform(X[:, i])
    onehotencoder = OneHotEncoder(handle_unknown='ignore')
    return onehotencoder

In [41]:
encode_function_train(1)

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='ignore', sparse=True)

In [42]:
X

array([[0, 32, 'v', ..., 0, 0, 0],
       [6, 32, 't', ..., 0, 0, 0],
       [7, 20, 'w', ..., 0, 0, 0],
       ...,
       [8412, 8, 'v', ..., 0, 0, 0],
       [8415, 9, 'r', ..., 0, 0, 0],
       [8417, 46, 'r', ..., 0, 0, 0]], dtype=object)

In [43]:
encode_function_train(2)

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='ignore', sparse=True)

In [44]:
encode_function_train(3)

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='ignore', sparse=True)

In [45]:
encode_function_train(4)

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='ignore', sparse=True)

In [46]:
encode_function_train(5)

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='ignore', sparse=True)

In [47]:
encode_function_train(6)

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='ignore', sparse=True)

In [48]:
encode_function_train(7)

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='ignore', sparse=True)

In [49]:
encode_function_train(8)

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='ignore', sparse=True)

In [50]:
X

array([[0, 32, 23, ..., 0, 0, 0],
       [6, 32, 21, ..., 0, 0, 0],
       [7, 20, 24, ..., 0, 0, 0],
       ...,
       [8412, 8, 23, ..., 0, 0, 0],
       [8415, 9, 19, ..., 0, 0, 0],
       [8417, 46, 19, ..., 0, 0, 0]], dtype=object)

In [51]:
# Convert X into a DataFrame

In [52]:
X_df = pd.DataFrame(X)
X_df

0   1   2   3   4   5   6   7   8   9    ... 355 356 357 358 359 360  \
0        0  32  23  17   0   3  24   9  14   0  ...   0   0   1   0   0   0   
1        6  32  21  19   4   3  28  11  14   0  ...   1   0   0   0   0   0   
2        7  20  24  34   2   3  27   9  23   0  ...   0   0   0   0   0   0   
3        9  20  21  34   5   3  27  11   4   0  ...   0   0   0   0   0   0   
4       13  20  23  34   5   3  12   3  13   0  ...   0   0   0   0   0   0   
...    ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..   
4204  8405   8  20  16   2   3   0   3  16   0  ...   1   0   0   0   0   0   
4205  8406  31  16  40   3   3   0   7   7   0  ...   0   1   0   0   0   0   
4206  8412   8  23  38   0   3   0   6   4   0  ...   0   0   1   0   0   0   
4207  8415   9  19  25   5   3   0  11  20   0  ...   0   0   0   0   0   0   
4208  8417  46  19   3   2   3   0   6  22   0  ...   1   0   0   0   0   0   

     361 362 363 364  
0      0   0   0   0  
1      0   0   0   0  
2      1   0   0   0  
3      0   0   0   0  
4      0   0   0   0  
...   ..  ..  ..  ..  
4204   0   0   0   0  
4205   0   0   0   0  
4206   0   0   0   0  
4207   0   0   0   0  
4208   0   0   0   0  

[4209 rows x 365 columns]

In [53]:
y

0       130.81
1        88.53
2        76.26
3        80.62
4        78.02
         ...  
4204    107.39
4205    108.77
4206    109.22
4207     87.48
4208    110.85
Name: y, Length: 4209, dtype: float64

In [54]:
# Convert y into a DataFrame

In [55]:
y_df = pd.DataFrame(y)
y_df

y
0     130.81
1      88.53
2      76.26
3      80.62
4      78.02
...      ...
4204  107.39
4205  108.77
4206  109.22
4207   87.48
4208  110.85

[4209 rows x 1 columns]

In [56]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X = scaler.fit_transform(X_df)
X

array([[-1.72565045,  0.16301209,  1.39348787, ..., -0.04081511,
        -0.02180363, -0.03778296],
       [-1.72318873,  0.16301209,  1.15902093, ..., -0.04081511,
        -0.02180363, -0.03778296],
       [-1.72277844, -0.71055977,  1.51072134, ..., -0.04081511,
        -0.02180363, -0.03778296],
       ...,
       [ 1.72568262, -1.58413164,  1.39348787, ..., -0.04081511,
        -0.02180363, -0.03778296],
       [ 1.72691348, -1.51133398,  0.924554  , ..., -0.04081511,
        -0.02180363, -0.03778296],
       [ 1.72773405,  1.18217927,  0.924554  , ..., -0.04081511,
        -0.02180363, -0.03778296]])

In [57]:
# Apply PCA for X

In [58]:
from mlxtend.preprocessing import standardize
from sklearn.decomposition import PCA

In [124]:
X = standardize(X)
X

0         1         2         3         4         5         6    \
0    -1.725650  0.163012  1.393488 -0.028122 -1.678270  0.028938  1.292117   
1    -1.723189  0.163012  1.159021  0.155388  0.620969  0.028938  1.776974   
2    -1.722778 -0.710560  1.510721  1.531709 -0.528650  0.028938  1.655760   
3    -1.721958 -0.710560  1.159021  1.531709  1.195779  0.028938  1.655760   
4    -1.720317 -0.710560  1.393488  1.531709  1.195779  0.028938 -0.162454   
...        ...       ...       ...       ...       ...       ...       ...   
4204  1.722811 -1.584132  1.041787 -0.119876 -0.528650  0.028938 -1.617026   
4205  1.723221  0.090214  0.572854  2.082237  0.046160  0.028938 -1.617026   
4206  1.725683 -1.584132  1.393488  1.898728 -1.678270  0.028938 -1.617026   
4207  1.726913 -1.511334  0.924554  0.705916  1.195779  0.028938 -1.617026   
4208  1.727734  1.182179  0.924554 -1.312688 -0.528650  0.028938 -1.617026   

           7         8         9    ...       355       356       357  \
0     0.751787  0.339445 -0.116122  ... -0.684167 -0.246447  1.475332   
1     1.437511  0.339445 -0.116122  ...  1.461630 -0.246447 -0.677814   
2     0.751787  1.618389 -0.116122  ... -0.684167 -0.246447 -0.677814   
3     1.437511 -1.081605 -0.116122  ... -0.684167 -0.246447 -0.677814   
4    -1.305384  0.197340 -0.116122  ... -0.684167 -0.246447 -0.677814   
...        ...       ...       ...  ...       ...       ...       ...   
4204 -1.305384  0.623655 -0.116122  ...  1.461630 -0.246447 -0.677814   
4205  0.066063 -0.655290 -0.116122  ... -0.684167  4.057675 -0.677814   
4206 -0.276798 -1.081605 -0.116122  ... -0.684167 -0.246447  1.475332   
4207  1.437511  1.192075 -0.116122  ... -0.684167 -0.246447 -0.677814   
4208 -0.276798  1.476285 -0.116122  ...  1.461630 -0.246447 -0.677814   

          358       359       360        361       362       363       364  
0    -0.14528 -0.097952 -0.090243  -0.087527 -0.040815 -0.021804 -0.037783  
1    -0.14528 -0.097952 -0.090243  -0.087527 -0.040815 -0.021804 -0.037783  
2    -0.14528 -0.097952 -0.090243  11.425027 -0.040815 -0.021804 -0.037783  
3    -0.14528 -0.097952 -0.090243  -0.087527 -0.040815 -0.021804 -0.037783  
4    -0.14528 -0.097952 -0.090243  -0.087527 -0.040815 -0.021804 -0.037783  
...       ...       ...       ...        ...       ...       ...       ...  
4204 -0.14528 -0.097952 -0.090243  -0.087527 -0.040815 -0.021804 -0.037783  
4205 -0.14528 -0.097952 -0.090243  -0.087527 -0.040815 -0.021804 -0.037783  
4206 -0.14528 -0.097952 -0.090243  -0.087527 -0.040815 -0.021804 -0.037783  
4207 -0.14528 -0.097952 -0.090243  -0.087527 -0.040815 -0.021804 -0.037783  
4208 -0.14528 -0.097952 -0.090243  -0.087527 -0.040815 -0.021804 -0.037783  

[4209 rows x 365 columns]

In [125]:
pca = PCA(n_components=0.95)
pca.fit(X)

X_pca = pca.transform(X)
X_pca

array([[12.2479426 , -2.94616767, -0.96889421, ..., -0.28937068,
        -0.0385096 , -0.40797343],
       [-0.10761082,  0.3647402 ,  0.98997272, ..., -1.3717079 ,
         2.17145055,  2.922418  ],
       [10.27291072, 21.10326107, -5.02216176, ...,  2.22406003,
         1.17365347,  0.95071053],
       ...,
       [ 0.44231616,  0.8989563 ,  3.45276206, ...,  0.28483857,
         0.20170045,  0.08086399],
       [-1.33649135,  0.59062955, -0.10217684, ...,  0.6743827 ,
         0.71578614, -0.65776366],
       [-2.16301364, -1.05903452, -0.28051994, ...,  0.51447754,
         0.04117558, -0.21727284]])

In [126]:
X_pca_df = pd.DataFrame(X_pca)
X_pca_df

0          1         2          3         4          5    \
0     12.247943  -2.946168 -0.968894   2.013795 -1.536963  -3.580114   
1     -0.107611   0.364740  0.989973   1.157325 -2.591086  -0.029973   
2     10.272911  21.103261 -5.022162  -4.472197  0.883294   2.575076   
3      7.356678  21.366669 -6.007828   0.231625  1.996314   0.701295   
4      6.570844  21.440453 -6.555632   0.933599  1.997617  -0.014757   
...         ...        ...       ...        ...       ...        ...   
4204  -0.233255   0.189347  4.196428  -3.991425 -1.005698   0.206496   
4205  11.950699  -2.808110 -0.842516  12.179215  5.923252 -17.960547   
4206   0.442316   0.898956  3.452762  -4.667339 -0.614467  -0.306319   
4207  -1.336491   0.590630 -0.102177   5.667796 -0.264367  -0.389586   
4208  -2.163014  -1.059035 -0.280520   2.637195 -2.268691  -0.143956   

            6         7          8         9    ...       139        140  \
0      9.039405 -3.627494 -16.145000  8.523040  ... -0.026020  -0.148302   
1      1.010086 -0.590471  -0.504041  0.164484  ...  1.452838   0.644448   
2      1.156838  3.640148  -0.925473  1.319942  ... -0.295349 -11.720078   
3      0.432205 -0.053416   0.237419  2.899095  ... -0.137796   2.028844   
4     -0.976966 -0.244026   0.928775  0.786463  ...  0.791125 -12.647709   
...         ...       ...        ...       ...  ...       ...        ...   
4204   1.691108  2.865604   0.698517 -0.343503  ... -0.598239   1.395927   
4205  11.901282  4.959376  20.625907 -4.449473  ... -0.456946  -0.144067   
4206   4.276500 -3.439990   0.251775  2.453027  ...  0.122402   0.674845   
4207  -3.996754 -0.390215  -0.772604  1.532407  ...  0.782379   0.581685   
4208   0.088701 -1.609403  -0.542336 -0.661732  ...  0.664973  -0.005247   

           141       142       143       144       145       146       147  \
0    -0.245132  0.232260 -0.282151 -0.010568  0.047192 -0.289371 -0.038510   
1    -0.412671 -1.104566  0.800997  1.560318  0.092357 -1.371708  2.171451   
2    -7.479800  0.831179  1.148745 -3.271447  1.070631  2.224060  1.173653   
3     0.865409  0.603601  0.237706 -0.284164  0.393171 -0.354771 -0.126093   
4    -8.754083  2.247402  2.536795 -6.345106  1.992118  3.321691  2.258430   
...        ...       ...       ...       ...       ...       ...       ...   
4204  0.987554 -0.152906  0.288671  0.278691 -0.429174 -0.563345 -0.539210   
4205 -0.052340  0.432624 -0.771161 -0.659608  0.244299 -0.437592  0.167176   
4206  0.142378 -0.109205  0.051637 -0.157748  0.099980  0.284839  0.201700   
4207  0.606092  1.009667 -0.671164  0.296183  0.168411  0.674383  0.715786   
4208  0.564884 -0.310100 -0.659790  0.294016  0.410065  0.514478  0.041176   

           148  
0    -0.407973  
1     2.922418  
2     0.950711  
3    -0.474009  
4     2.042327  
...        ...  
4204  0.059089  
4205  0.247487  
4206  0.080864  
4207 -0.657764  
4208 -0.217273  

[4209 rows x 149 columns]

In [62]:
# Create train and test split sets for X and y variables

In [127]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_pca_df, y_df, test_size=0.3,random_state=0)

In [128]:
# Import the necessary packages

In [129]:
from sklearn.linear_model import ElasticNet
from sklearn.linear_model import Lasso
from xgboost import XGBRegressor
from sklearn.metrics import accuracy_score

In [130]:
# Initialize ElasticNet Regressor

In [131]:
#regr = Lasso(random_state=0)
#regr.fit(X_train, y_train)

#print(regr.coef_)

#print(regr.intercept_)

# Prediction for Test Dataset using ElasticNet Regressor

#y_pred = regr.predict(X_test)
#y_pred

In [132]:
# Creating a model using XGBRegressor
# max_depth=3, learning_rate=0.1, n_estimators=100, verbosity=1, objective='reg:squarederror', booster='gbtree', tree_method='auto', n_jobs=1, gamma=0

In [133]:
model = XGBRegressor(min_child_weight=1, max_depth=5, max_delta_step=0, alpha=0, scale_pos_weight=1, learning_rate=0.1, n_estimators=100, verbosity=1, eta=0.3, objective='reg:squarederror', silent=0, booster='gbtree', tree_method='auto', n_jobs=1, gamma=0)
model.fit(X_train, y_train)

XGBRegressor(alpha=0, base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, eta=0.3, gamma=0,
             importance_type='gain', learning_rate=0.1, max_delta_step=0,
             max_depth=5, min_child_weight=1, missing=None, n_estimators=100,
             n_jobs=1, nthread=None, objective='reg:squarederror',
             random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
             seed=None, silent=0, subsample=1, tree_method='auto', verbosity=1)

In [134]:
# Prediction for Test Dataset using XGBRegressor

In [135]:
y_predi = model.predict(X_test)

In [136]:
y_predi

array([107.942474,  92.36569 , 111.96488 , ..., 114.76768 ,  93.023834,
        98.44776 ], dtype=float32)

In [137]:
# Accuracy metrics

In [138]:
import sklearn.metrics

In [139]:
r2_score = sklearn.metrics.r2_score(y_test, y_predi)
print('r2_score: {0}'.format(r2_score))

r2_score: 0.43410291155663516


In [140]:
adjusted_r_squared = 1 - (1-r2_score)*(len(y_predi)-1)/(len(y_predi)-X_test.shape[1]-1)
adjusted_r_squared
print('adjusted_r_squared: {0}'.format(adjusted_r_squared))

adjusted_r_squared: 0.3583449006149808
